### PR TITLE
ORM 2.4 to 2.5

### PR DESCRIPTION
**Pull request by ineilson**
All tests pass and web interface and PI appear functional, but without extensive checking. Includes a commit of the composer lock file generated before any ORM changes.

### CODE REVIEW

**Review by gregcorbett — APPROVED** [review]
LGTM

**Comment by gregcorbett** [comment]
Supersedes #334

**Comment by gregcorbett** [comment]
Can you rebase this ontop of the latest dev and give it once over that it still works?

**Comment by ineilson** [comment]
> Can you rebase this ontop of the latest dev and give it once over that it still works?

Rebased and still works.

**Pull request merged**
