### PR TITLE
Extend write API to allow editing of site and endpoint properties

### PR DESCRIPTION
**Pull request by GRyall**
Opening this pull request to allow me to share progress on the write API and check unit tests. 

Delivers 4 of 7 promised new write API methods 
- Enables editing of individual endpoint properties using PUT and POST and specifying the property in the URL
- Enables editing of individual service properties using PUT and POST and specifying the property in the URL

Depends on ~#157, #161, #177, #179, #180,  #187, #189~

### CODE REVIEW

**Comment by tofu-rocketry** [comment]
Pro-tip: [You can now create PRs as a draft.](https://help.github.com/en/articles/about-pull-requests#draft-pull-requests)

**Comment by GRyall** [comment]
This is now ready for review. One more pull request will complete the Write API extension.

Note: there are currently a high number of commits in this PR from other PRs (see opening comment for list)

**Comment by GRyall** [comment]
This has now been rebased to remove the conflict (I am not sure why there was a conflict or what it was, but there is not one now).

**Comment by GRyall** [comment]
I am closing this as it hasn't been reviewed and it will be simpler to review these changes as part of #190

**Pull request closed without merging**
