### PR TITLE
Fix code style issues in sample data deploy scripts

### LINKED ISSUE #481: Code style issues in sample data deploy directory
whilst working on #416, I noticed lots of code style issues (such as lines too long, no spaces after if statements, etc) within most of the files in the sample data deploy script directory (https://github.com/GOCDB/gocdb/tree/dev/lib/Doctrine/deploy). These get picked up by codeclimate and codacy.

### PR DESCRIPTION
**Pull request by rowan04**
- Add space before and after '.' concatenator
- Add space after if and foreach statements
- Splits up lines that are too long
- Improves syntax of comments
- Indentation fixes
- Adds and removes spaces in various areas

resolves #481 
Resolves GT-202

### CODE REVIEW

**Comment by gregcorbett** [comment]
> more changes to come.

Do mark this as ready for review once those changes are made 😄

**Comment by rowan04** [comment]
rebase to squash extra commit into previous commit

**Comment by rowan04** [comment]
update with rebase to latest dev

**Comment by gregcorbett** [comment]
rebasing on current dev

**Pull request merged**
