### PR TITLE
Update STFC logos to reflect new branding

### PR DESCRIPTION
**Pull request by GRyall**
This update replaces the old STFC logo with the new version. There is a cropped version for the portal, which is likely technically not in line with brand guidelines. However, the old cropped logo it replaces was not in line with the old guidelines either...

image

image

### CODE REVIEW

**Comment by tofu-rocketry** [comment]
What using about the "square lock-up", as they call it, for the small logos? Is the text in that just too small?

**Comment by GRyall** [comment]
> 
> 
> What using about the "square lock-up", as they call it, for the small logos? Is the text in that just too small?

It's not available for download from the page with all the logos. but here is a mock up:
image

**Comment by tofu-rocketry** [comment]
That is quite tiny. 🤔

**Comment by jrha** [comment]
Hmm, this is going to keep bugging me about the new logo, but the little tick at the top bothers me, as it shrinks the box and breaks the horizontal lines in the logo box, it might be too messy to fix, but could it be slightly larger?

Mockup:
image

**Comment by jrha** [comment]
Also... maybe now is the time to use vector based logos?

**Comment by ineilson** [comment]
> 
> 
> Hmm, this is going to keep bugging me about the new logo, but the little tick at the top bothers me, as it shrinks the box and breaks the horizontal lines in the logo box, it might be too messy to fix, but could it be slightly larger?
> 
> Mockup:
> image

Was just thinking exactly the same. That or move the UKRI box away from the EU one which dominates.

**Comment by GRyall** [comment]
I certainly agree about the need to use vector based logos. I am a little worried about getting different height logos to align correctly in a simple way.

**Comment by tofu-rocketry** [comment]
Shall we not worry about this for now for the purposes of this PR?

**Comment by jrha** [comment]
Pfft fine, I'll allow it.

**Comment by tofu-rocketry** [comment]
> Pfft fine, I'll allow it.

"Perfect is the enemy of good." ~ James Adams after Voltaire

**Comment by jrha** [comment]
I said I'd allow it…

**Pull request merged**
