### PR TITLE
Release 5.11.0 to dev

### PR DESCRIPTION
**Pull request by gregcorbett**

### CODE REVIEW

**Comment by gregcorbett** [comment]
I think codacy has gotten slightly confused and is showing the analysis of #506 here. The analysis of this PR gets a green tick: https://app.codacy.com/gh/GOCDB/gocdb/pullRequest?prid=13696382

**Comment by gregcorbett** [comment]
> but should be rebased.

`dev` has moved on since the release branch was created and now contains changes not tested within the context of the 5.11.0 release, and rebasing the release branch would incorporate those changes into the release.

Those changes will be released in the next version.

**Review by Sae126V — APPROVED** [review]
LGTM. But, I think we should wait @tofu-rocketry for an approval since he has made few comments.

**Comment by tofu-rocketry** [comment]
> `dev` has moved on since the release branch was created and now contains changes not tested within the context of the 5.11.0 release, and rebasing the release branch would incorporate those changes into the release.
> 
> Those changes will be released in the next version.

So the release will be a tag on `master` with the release branch merged in?

**Review by tofu-rocketry — APPROVED** [review]

**Pull request merged**
