### PR TITLE
Hotfix-update-momentdotjs to dev branch

### PR DESCRIPTION
**Pull request by RoseECooper**
Changing standard_header.php to fetch moment-with-locales.min.js from the cdn javascript library.

### CODE REVIEW

**Review by RoseECooper — COMMENTED** [review]
Changing standard_header.php to fetch moment-with-locales.min.js from the cdn javascript library.

**Review by gregcorbett — APPROVED** [review]
LGTM :)

**Review by gregcorbett — CHANGES_REQUESTED** [review]
See #356

**Review by gregcorbett — APPROVED** [review]

**Comment by gregcorbett** [comment]
See #356

**Pull request merged**
