### PR TITLE
Css update colour

### PR DESCRIPTION
**Pull request by CoolCoder2019**
This code changes the colour scheme of the website, and fixes a few bugs on the background.
Accept please  :) 👍 🥇

### CODE REVIEW

**Comment by CoolCoder2019** [comment]
I was planning to rebase once we merged #114

**Comment by CoolCoder2019** [comment]
I've sorted the capitalisation of the hex numbers.

**Comment by tofu-rocketry** [comment]
Could we see a demo of this?

**Comment by GRyall** [comment]
I've deleted the VM we had running this - but it would be easy enough to put onto a test instance of GOCDB  by anyone who wanted to see it.

**Comment by gregcorbett** [comment]
The green has grew on me...

**Pull request closed without merging**
