### PR TITLE
Unaccentuate "unaccentuated"

### LINKED ISSUE #303: Unaccentuate "unaccentuated"
Pretty sure these pages should say "unaccented" rather than "unaccentuated", right?

`htdocs/web_portal/views/user/edit_user.php`
`htdocs/web_portal/views/user/register.php`

There's two pages with two occurrences each: https://github.com/GOCDB/gocdb/search?q=unaccentuated

(Spotted in the screenshots in [this ticket](https://ggus.eu/index.php?mode=ticket_info&ticket_id=153994).)

### PR DESCRIPTION
**Pull request by ItsTino**
Resolves #303 
Update "unaccentuated" to "unaccented" in
htdocs/web_portal/views/user/edit_user.php
htdocs/web_portal/views/user/register.php

### CODE REVIEW

**Comment by tofu-rocketry** [comment]
Thanks! How did you come across this, @ItsTino ?

**Review by tofu-rocketry — APPROVED** [review]
Looks good.

**Comment by ItsTino** [comment]
> Thanks! How did you come across this, @ItsTino ?

Hi, I found this on a website that lists open source projects with issues marked 'good first issue'

**Comment by tofu-rocketry** [comment]
> Hi, I found this on a website that lists open source projects with issues marked 'good first issue'

Ah, nifty! Useful to know - gives an encouragement to triage issues reasonably.

**Pull request merged**
